------Joins -----------
 
/**1. Write a query to display the custid ,name, age, orderid,orderdate for 
product books or cd, sort data by name in descending order**/ 
select c.custid, c.custname, c.age, o.orderid, o.orderdate
from customers c
join orders o on c.custid = o.custid
join orderdetails od on o.orderid = od.orderid
join products p on od.productid = p.productid
where p.product in ('books','cd')
order by c.custname desc;

/**2. Write a SQL statement to find the list of customers who live in the 
same city as ajay, and display custid , custname , price (price > 500) **/
select c.custid, c.custname, o.price
from customers c
join orders o on c.custid = o.custid
where c.city = (
    select city from customers where custname = 'ajay'
)
and o.price > 500;

 
 
/**3. Write a query to find the name of customers along with order details 
who purchased   more than two products **/
select c.custname, o.orderid, od.productid, od.qty
from customers c
join orders o on c.custid = o.custid
join orderdetails od on o.orderid = od.orderid
where o.orderid in (
    select orderid
    from orderdetails
    group by orderid
    having count(productid) > 2
);


/**4. A discount of 20% has been announced to all customers who resides 
in Bangalore . display custid , custname , orderid  and discount price  **/
select c.custid, c.custname, o.orderid,
       (o.price * 0.80) as discount_price
from customers c
join orders o on c.custid = o.custid
where c.city = 'bangalore';

 
/**5. write a query to join three tables (create products table for the same) **/
select c.custname, o.orderid, p.product, p.price
from customers c
join orders o on c.custid = o.custid
join orderdetails od on o.orderid = od.orderid
join products p on od.productid = p.productid;


/**6. update price by 5% from orders table for customers who resides in 
pune and chennai **/
update orders
set price = price * 1.05
where custid in (
    select custid from customers where city in ('pune','chennai')
);

/**7. create a report in following format 
 
Custidord Custname Product Price orderdate 
cid:100-ordid:1     
1. Custname should be uppercase 
2. Display only first 3 character of product 
3.  The report should be of December 2000 **/
select
    'cid:' + cast(c.custid as varchar) + '-ordid:' + cast(o.orderid as varchar) as custidord,
    upper(c.custname) as custname,
    left(p.product,3) as product,
    od.price,
    o.orderdate
from customers c
join orders o on c.custid = o.custid
join orderdetails od on o.orderid = od.orderid
join products p on od.productid = p.productid
where month(o.orderdate) = 12
and year(o.orderdate) = 2000;

 
 
 
 
 
--Validations 
 
/**Create Table Students 
 
StudentRollNumber 
StudentName 
DOB 
Class 
I. Student Roll Number should be  autogenerated as (100,200,300…). 
Alter Command 
a. DOB cannot be greater then current date 
b. Class should be between 1 - 10 **/
create table students (
    studentrollnumber int identity(100,100) primary key,
    studentname varchar(50),
    dob date,
    class int
);
--a
alter table students
add constraint chk_dob check (dob <= getdate());

 
/**Create Table Stock 
StockId 
MinStockLvl 
MaxStockLvl 
 
Alter Command 
The MaxStockLvl should be Greater than MinStockLvl. 
Stock id should be following format 
stc-11-aaa 
Start with 3 alphabets following by – followed by 2 digit followed by – and 
ending with 3 alphabets . **/
create table stock (
    stockid varchar(20),
    minstoklvl int,
    maxstoklvl int
);

alter table stock
add constraint chk_stocklvl check (maxstoklvl > minstoklvl);

alter table stock
add constraint chk_stockid
check (stockid like '[a-z][a-z][a-z]-[0-9][0-9]-[a-z][a-z][a-z]');

 
 
/**Create Table purchase 
 
Productid 
PurchaseDate 
Serialno 
Price 
Qty  
Total 
 
• The default value for purchase date should be the system date. 
• Serialno  should be a unique  
• Total to be autogenerated 
• Create a rule  qty should be greater than 1 
• Create a rule where price should be between 1000 and  7000**/
create table purchase (
    productid int,
    purchasedate date default getdate(),
    serialno varchar(50) unique,
    price int,
    qty int,
    total as (price * qty)
);

alter table purchase
add constraint chk_qty check (qty > 1);

alter table purchase
add constraint chk_price check (price between 1000 and 7000);
